name: Backend Continuous Integration

on:
  pull_request:
    branches: [main]
    paths:
      - 'starter/backend/**'
      - '.github/workflows/backend-ci.yaml'
  workflow_dispatch:

env:
  WORKING_DIRECTORY: starter/backend
  PIPENV_NOSPIN: '1'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
          cache-dependency-path: starter/backend/Pipfile.lock
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev --deploy
      - name: Lint
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
          cache-dependency-path: starter/backend/Pipfile.lock
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --dev --deploy
      - name: Test
        run: pipenv run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build --tag mp-backend:${{ github.sha }} starter/backend
